# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # Oracle数据库时打开
    # driver-class-name: oracle.jdbc.driver.OracleDriver
    # url: jdbc:oracle:thin:@localhost:1521:XE
    # username: test
    # password: test_password

# 日志配置
logging:
  level:
    org.springframework: warn
    com.warm: debug

# warm-flow工作流配置
warm-flow:
  # 是否显示banner图，默认是
  banner: true
  # 填充器 （可配置文件注入，也可用@Bean/@Component方式）
#  data-fill-handler-path: com.warm.flow.core.test.handle.CustomDataFillHandler
  # 全局租户处理器（可配置文件注入，也可用@Bean/@Component方式）
#  tenant_handler_path: com.warm.flow.core.test.handle.CustomTenantHandler
  # 是否开启逻辑删除
  logic_delete: true
  # 逻辑删除字段值（开启后默认为2）
  logic_delete_value: 2
  # 逻辑未删除字段（开启后默认为0）
  logic_not_delete_value: 0